Repository BB-Computer-Enterprises/web3jobs, pull requests merged in 2021-11, with the labels that each got.

#34 [WIP] Company Page UI
  package.json
  src/components/PageContainer.js
  src/components/pages/AllCompaniesPage.js
  src/components/pages/AllJobsPage.js
  src/components/pages/CompanyPage.js
  src/components/pages/JobItemPage.js
  src/components/pages/PostAJobPage.js
  src/config/constants.js
Labels: enhancement

#35 Companies page is ready!
  package.json
  src/components/pages/CompanyPage.js
  src/config/constants.js
Labels: enhancement

#36 Job description uses Markdown now
  package-lock.json
  package.json
  src/components/pages/JobItemPage.js
Labels: enhancement

#37 Feature/iPadStyles
  build/asset-manifest.json
  build/index.html
  build/static/js/2.2072008c.chunk.js
  build/static/js/2.2072008c.chunk.js.LICENSE.txt
  build/static/js/2.2072008c.chunk.js.map
  build/static/js/main.f25a7d1c.chunk.js
  build/static/js/main.f25a7d1c.chunk.js.map
  src/components/Header.js
  src/components/JobsList.js
  src/components/PageContainer.js
  src/components/pages/CompanyPage.js
  src/components/pages/HomePage.js
  src/components/pages/JobItemPage.js
  src/config/constants.js
  src/util/genListIcon.js
Labels: bug, enhancement

#38 Added sign up field validation
  package.json
  src/components/pages/CompanyPage.js
  src/components/pages/HomePage.js
  src/components/pages/JobItemPage.js
  src/config/constants.js
  src/lib/api.js
Labels: enhancement

#40 discord icon
  package.json
  src/components/Footer.js
Labels: enhancement

#41 Feature/twitter cards
  package-lock.json
  package.json
  src/components/JobsList.js
  src/components/pages/AllJobsPage.js
  src/components/pages/CompanyPage.js
  src/components/pages/HomePage.js
  src/components/pages/JobItemPage.js
  src/components/pages/PostAJobPage.js
  src/util/genLinkCard.js
  src/util/index.js
Labels: enhancement

#42 [WIP] Feature/fixing routing
  package-lock.json
  package.json
  src/components/pages/AllCompaniesPage.js
  src/components/pages/CompanyPage.js
  src/components/pages/JobItemPage.js
  src/config/constants.js
  src/lib/database/dbCompanies.js
  src/lib/database/dbJobs.js
Labels: bug

#43 added fathom analytics
  package.json
  public/index.html
Labels: enhancement
